[versions]
kotlin = "1.9.24"
shadow-jar = "8.1.1"
okhttp = "4.12.0"
kotlinx-serialization-json = "1.6.3"
tomlj = "1.1.1"
ktlint = "12.1.1"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
# TODO: Use https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp-coroutines later
okhttp-coroutines = { module = "ru.gildor.coroutines:kotlin-coroutines-okhttp", version = "1.0" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
tomlj = { module = "org.tomlj:tomlj", version.ref = "tomlj" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow-jar = { id = "com.github.johnrengelman.shadow", version.ref = "shadow-jar" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }